plugins { id 'com.android.application'; id 'com.google.gms.google-services' }

android {
    namespace 'com.kenleposa.dealrecon'
    compileSdk 35

    defaultConfig {
        applicationId 'com.kenleposa.dealrecon'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '1.0.0'
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.18.0')
    implementation 'com.google.firebase:firebase-ai'
    implementation 'com.google.firebase:firebase-appcheck-debug'
    implementation 'com.google.guava:guava:31.0.1-android'
}
